erver:
  port: 8190
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BavatharanyM/spring-clous-config
          search-paths:
           - '*service'
